(() => {
  const config = window.LELYS_CONFIG || {};
  const productGrid = document.querySelector('#product-grid');
  const menuStatus = document.querySelector('#menu-status');
  const menuFallback = document.querySelector('#menu-fallback');
  const hotplateLink = document.querySelector('#hotplate-link');
  const footerHotplateLink = document.querySelector('#footer-hotplate-link');
  const toast = document.querySelector('#toast');
  const heroProductName = document.querySelector('#hero-product-name');
  const heroProductImage = document.querySelector('#hero-product-image');
  const escapeHtml = (value = '') => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
  const normalizePhone = value => String(value || '').replace(/\D/g, '');
  function showToast(message) { toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 3500); }
  function smsHref(message) { const phone = normalizePhone(config.orderPhone); if (!phone) return null; const separator = /iPhone|iPad|iPod/i.test(navigator.userAgent) ? '&' : '?'; return `sms:+${phone}${separator}body=${encodeURIComponent(message)}`; }
  function openSms(message = config.defaultMessage) { const href = smsHref(message || "Hi! I'd like to request an order from Lely's Bread."); if (!href) { showToast('The ordering phone number still needs to be connected.'); return; } window.location.href = href; }
  function bindOrderButtons(scope = document) { scope.querySelectorAll('.js-order').forEach(button => { if (button.dataset.bound) return; button.dataset.bound = 'true'; button.addEventListener('click', () => { const product = button.dataset.product; const message = product ? `Hi! I'd like to request an order for ${product} from Lely's Bread. Is it available?` : config.defaultMessage; openSms(message); }); }); }
  function productCard(product, index) { const title = product.title || 'Fresh-baked favorite'; const image = product.image || (index % 2 ? '/assets/cinnamon-rolls-detail.jpg' : '/assets/cinnamon-rolls-hero.jpg'); const description = product.description || 'Fresh-milled, small-batch, and made with thoughtfully chosen ingredients.'; const price = product.price ? `$${Number(product.price).toFixed(2)}` : 'Ask for price'; const availability = product.available === false ? 'Ask about next bake' : 'Request availability'; return `<article class="product-card reveal"><span class="product-badge">${escapeHtml(availability)}</span><div class="product-image"><img src="${escapeHtml(image)}" alt="${escapeHtml(title)}" loading="lazy" /></div><div class="product-body"><div class="product-meta"><h3>${escapeHtml(title)}</h3><span class="product-price">${escapeHtml(price)}</span></div><p class="product-description">${escapeHtml(description)}</p><div class="product-actions"><button class="button js-order" data-product="${escapeHtml(title)}" type="button">Request this item by text</button></div></div></article>`; }
  async function loadMenu() { try { const response = await fetch(`/api/menu?chefId=${encodeURIComponent(config.hotplateSlug || 'lelysbread')}`, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error(`Menu request failed: ${response.status}`); const data = await response.json(); const products = Array.isArray(data.products) ? data.products : []; if (!products.length) throw new Error('No public products returned'); productGrid.innerHTML = products.map(productCard).join(''); menuStatus.textContent = data.eventTitle ? `Showing products from “${data.eventTitle}.”` : 'Showing the latest public Hotplate menu.'; menuFallback.hidden = true; const featured = products.find(item => item.image) || products[0]; if (featured) { heroProductName.textContent = featured.title || 'Fresh-baked favorites'; if (featured.image) { heroProductImage.src = featured.image; heroProductImage.alt = featured.title || "Fresh-baked item from Lely's Bread"; } } bindOrderButtons(productGrid); observeReveals(productGrid); } catch (error) { console.warn(error); menuStatus.textContent = 'The live Hotplate menu is not available right now.'; menuFallback.hidden = false; } }
  function observeReveals(scope = document) { const items = scope.querySelectorAll('.reveal:not([data-observed])'); if (!('IntersectionObserver' in window)) { items.forEach(item => item.classList.add('visible')); return; } const observer = new IntersectionObserver(entries => { entries.forEach(entry => { if (!entry.isIntersecting) return; const delay = Number(entry.target.dataset.delay || 0); window.setTimeout(() => entry.target.classList.add('visible'), delay); observer.unobserve(entry.target); }); }, { threshold: .12 }); items.forEach(item => { item.dataset.observed = 'true'; observer.observe(item); }); }
  function setupNavigation() { const toggle = document.querySelector('.menu-toggle'); const nav = document.querySelector('.site-nav'); toggle?.addEventListener('click', () => { const isOpen = nav.classList.toggle('open'); toggle.setAttribute('aria-expanded', String(isOpen)); }); nav?.querySelectorAll('a, button').forEach(item => item.addEventListener('click', () => { nav.classList.remove('open'); toggle?.setAttribute('aria-expanded', 'false'); })); }
  function setupGuide() { const dialog = document.querySelector('#guide-dialog'); document.querySelector('#open-guide')?.addEventListener('click', () => dialog?.showModal()); document.querySelector('#close-guide')?.addEventListener('click', () => dialog?.close()); dialog?.addEventListener('click', event => { if (event.target === dialog) dialog.close(); }); }
  function addStructuredData() { const phone = normalizePhone(config.orderPhone); const schema = { '@context': 'https://schema.org', '@type': 'Bakery', name: "Lely's Bread", description: 'Fresh-milled flour baked goods made in small batches with thoughtfully chosen ingredients.', areaServed: config.locationLabel || 'Wellington, Florida', url: window.location.href }; if (phone) schema.telephone = `+${phone}`; const node = document.createElement('script'); node.type = 'application/ld+json'; node.textContent = JSON.stringify(schema); document.head.appendChild(node); }
  if (config.hotplateUrl) { hotplateLink.href = config.hotplateUrl; footerHotplateLink.href = config.hotplateUrl; }
  bindOrderButtons(); setupNavigation(); setupGuide(); addStructuredData(); observeReveals(); loadMenu();
})();
