const HOTPLATE_API = 'https://bets.hotplate.com/trpc';
function unwrap(value){if(value==null)return value;if(Array.isArray(value))return value.map(unwrap);if(typeof value!=='object')return value;if(Object.prototype.hasOwnProperty.call(value,'json'))return unwrap(value.json);if(Object.prototype.hasOwnProperty.call(value,'data')&&Object.keys(value).length<=3)return unwrap(value.data);if(Object.prototype.hasOwnProperty.call(value,'result')&&Object.keys(value).length<=3)return unwrap(value.result);const output={};for(const [key,item] of Object.entries(value))output[key]=unwrap(item);return output}
async function callHotplate(procedure,input){const shapes=[input,{json:input}];let lastError;for(const shape of shapes){try{const url=`${HOTPLATE_API}/${procedure}?input=${encodeURIComponent(JSON.stringify(shape))}`;const response=await fetch(url,{headers:{accept:'application/json','user-agent':'LelysBreadWebsite/1.0'},signal:AbortSignal.timeout(9000)});if(!response.ok)throw new Error(`${procedure} returned ${response.status}`);const payload=await response.json();const data=unwrap(payload);if(data?.error)throw new Error(data.error.message||`${procedure} failed`);return data}catch(error){lastError=error}}throw lastError||new Error(`${procedure} failed`)}
function findArraysByKey(value,keyPattern,found=[]){if(!value||typeof value!=='object')return found;if(Array.isArray(value)){value.forEach(item=>findArraysByKey(item,keyPattern,found));return found}for(const [key,item] of Object.entries(value)){if(keyPattern.test(key)&&Array.isArray(item))found.push(item);findArraysByKey(item,keyPattern,found)}return found}
function pickEvents(value){const preferred=findArraysByKey(value,/(liveEvents|pastEvents|events)$/i).flat();const generic=preferred.length?preferred:findArraysByKey(value,/event/i).flat();return generic.filter(item=>item&&typeof item==='object'&&(item.id||item.eventId||item.title))}
function imageUrl(value){if(!value)return'';if(typeof value==='string')return value;if(typeof value!=='object')return'';return value.cdnUrl||value.url||value.originalUrl||value.src||value.fileUrl||value.imageUrl||''}
function stripHtml(value=''){return String(value).replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim()}
function candidateItems(value,found=[]){if(!value||typeof value!=='object')return found;if(Array.isArray(value)){value.forEach(item=>candidateItems(item,found));return found}const looksLikeProduct=(value.title||value.name)&&(value.price!=null||value.description||value.image||value.inventoryInfo)&&!value.goLiveTime;if(looksLikeProduct)found.push(value);for(const item of Object.values(value))candidateItems(item,found);return found}
function normalizeProduct(item){const inventory=item.inventoryInfo||item.inventory||{};const rawPrice=item.price?.amount??item.price??item.unitPrice??item.basePrice;const parsedPrice=Number(String(rawPrice??'').replace(/[^0-9.]/g,''));const soldOut=item.isSoldOut===true||inventory.available===0||inventory.remaining===0;return{id:String(item.id||item.menuItemId||item.eventMenuItemId||item.slug||item.title||item.name),title:stripHtml(item.title||item.name||'Fresh-baked favorite'),description:stripHtml(item.description||item.subtitle||item.details||''),price:Number.isFinite(parsedPrice)?parsedPrice:null,image:imageUrl(item.image||item.photo||item.thumbnail||item.images?.[0]),available:!soldOut,category:stripHtml(item.sectionName||item.category||item.type||'')}}
function dedupeProducts(items){const seen=new Map();for(const raw of items){const item=normalizeProduct(raw);const key=item.title.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();if(!key||key.length<2)continue;const existing=seen.get(key);if(!existing||(!existing.image&&item.image)||(!existing.description&&item.description))seen.set(key,item)}return[...seen.values()].slice(0,24)}
function eventId(event){return event?.id||event?.eventId||event?.uuid||null}
export default async function handler(request,response){response.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=1800');response.setHeader('Access-Control-Allow-Origin','*');const chefId=String(request.query?.chefId||'lelysbread').replace(/[^a-zA-Z0-9_-]/g,'')||'lelysbread';try{const[settingsResult,liveResult,pastResult]=await Promise.allSettled([callHotplate('shop.getChefSiteSettings',{chefId}),callHotplate('shop.getPublicLiveEvents',{chefId}),callHotplate('shop.getPublicPastEvents',{chefId,direction:'forward'})]);const settings=settingsResult.status==='fulfilled'?settingsResult.value:{};const liveEvents=liveResult.status==='fulfilled'?pickEvents(liveResult.value):[];const pastEvents=pastResult.status==='fulfilled'?pickEvents(pastResult.value):[];const events=[...liveEvents,...pastEvents].filter((event,index,list)=>{const id=eventId(event);return id&&list.findIndex(candidate=>eventId(candidate)===id)===index});let sourceEvent=liveEvents[0]||pastEvents[0]||null;let itemCandidates=candidateItems(liveResult.status==='fulfilled'?liveResult.value:{});itemCandidates.push(...candidateItems(pastResult.status==='fulfilled'?pastResult.value:{}));for(const event of events.slice(0,6)){const id=eventId(event);if(!id)continue;try{const detail=await callHotplate('shop.getEvent',{eventId:id,fulfillmentType:'ALL'});const items=candidateItems(detail);if(items.length&&!sourceEvent)sourceEvent=event;itemCandidates.push(...items)}catch{}}const products=dedupeProducts(itemCandidates);const site=unwrap(settings)||{};const restaurantName=site.restaurantName||site.name||site.chef?.restaurantName||"Lely's Bread";const about=stripHtml(site.aboutSection||site.about||site.description||'');response.status(200).json({chefId,restaurantName,about,eventTitle:sourceEvent?.title||sourceEvent?.name||'',products,source:'Hotplate public storefront data',updatedAt:new Date().toISOString()})}catch(error){response.status(502).json({chefId,products:[],error:'The public Hotplate menu could not be loaded.',detail:process.env.NODE_ENV==='development'?String(error?.message||error):undefined})}}
